name: NPM Publish

on:
  push:
    branches:
      - main
      - master
    tags:
      - "v*"
  workflow_dispatch: # Allow manual triggering

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Check package version
        id: check-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          MINOR_VERSION=$(echo $VERSION | cut -d '.' -f2)
          IS_EVEN=$((MINOR_VERSION % 2 == 0))
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "is_even=$IS_EVEN" >> $GITHUB_OUTPUT
          echo "Package version: $VERSION (Minor: $MINOR_VERSION, Is Even: $IS_EVEN)"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Publish to NPM (even versions only)
        if: ${{ steps.check-version.outputs.is_even == '1' }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Don't publish (odd version)
        if: ${{ steps.check-version.outputs.is_even == '0' }}
        run: echo "Skipping publication because ${{ steps.check-version.outputs.version }} has an odd minor version."
